/* Generated By:JavaCC: Do not edit this line. AnalisadorLexico.java */
package Analisadores;
import EstruturasDados.AreaInstrucao;
import EstruturasDados.First;import EstruturasDados.RecoverySet;

import java.util.ArrayList;

public class AnalisadorLexico implements AnalisadorLexicoConstants {
    static int nCountSintaticError = 0;
    private static boolean eof = false;
    private static StringBuffer mensagens_erros_sintatic = new StringBuffer();
    public String getMessages() {
        return this.token_source.getMensagesManhosas();
     }
    public static boolean isSucesso;
    public static AnalisadorSemantico analisadorSemantico = new AnalisadorSemantico();

    public int getLexError() {
       return this.token_source.foundLexError();
    }
    public int getSintaticError() {
           return this.nCountSintaticError;
    }
    public static void acaoSemantica(String codigo){
        String argumento = "";
       // try {
        analisadorSemantico.analisarSemantica(codigo, argumento);
       // }catch (StringIndexOutOfBounds e){
            //System.out.println("Erro na análise semântica");
       // }

    }
    public ArrayList<AreaInstrucao> getCodInter(){
        return analisadorSemantico.getCodIntermed();
    }

    public int  getNumErrSemantic(){
        return analisadorSemantico.getNumErrSemantico();
    }

    public String getMsgErrSemantic(){
        String retorno = analisadorSemantico.getMensagensErros();
        return retorno;
    }
    public String getMensagensErros() {
       return this.token_source.getMensagensErros();
    }
   public String getMsgSintaticError() {
          return this.mensagens_erros_sintatic.toString();
       }

   public static void consumeUntil(RecoverySet g, ParseException e, String met)throws ParseException{
        Token tok;
        if(g == null) throw e;
        tok = getToken(1);
        while(!eof){
            if(g.contains(tok.kind)){
                break;
            }
            getNextToken();
            tok = getToken(1);
            if(tok.kind == EOF && !g.contains(EOF)) eof = true;
        }
        nCountSintaticError += 1;
        mensagens_erros_sintatic.append(e.getMessage());
        if(eof) throw  new ParseException("\nERRO (04)---> Programa não foi finalizado corretamente\nEncontrado EOF na linha " + tok.beginLine + " coluna " + tok.beginColumn + " \n" );
   }
   public static String im(int x){
        int k;
        String s;

        s = tokenImage[x];
        k = s.lastIndexOf("\"");
        try{s = s.substring(1,k);}
        catch (StringIndexOutOfBoundsException e){ }
        return s;
   }

  static final public void program() throws ParseException {
    RecoverySet g = First.program;
    try {
      comentario();
      jj_consume_token(PROGRAM);
      jj_consume_token(ACHAVE);
      declaracao_variaveis();
      corpo_do_programa();
      jj_consume_token(FCHAVE);
      identificador_programa();
         acaoSemantica("#1");
      jj_consume_token(0);
    } catch (ParseException e) {
        if(token_source.foundLexError() == 0) {
            consumeUntil(g, e, "program");
        }
    }
  }

  static final public void declaracao_variaveis() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DEFINE:
      define();
      break;
    default:
      jj_la1[0] = jj_gen;

    }
  }

  static final public void define() throws ParseException {
    RecoverySet g = First.define;
    try {
      jj_consume_token(DEFINE);
      jj_consume_token(ACHAVE);
      estrutura_define();
      jj_consume_token(FCHAVE);
    } catch (ParseException e) {
        if(token_source.foundLexError() == 0) {
           consumeUntil(g, e, "program");
        }
    }
  }

  static final public void estrutura_define() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NOT:
      constante();
      chama_variavel();
      break;
    case VARIABLE:
      variavel();
      chama_constante();
      break;
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void chama_variavel() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VARIABLE:
      variavel();
      break;
    default:
      jj_la1[2] = jj_gen;

    }
  }

  static final public void chama_constante() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NOT:
      constante();
      break;
    default:
      jj_la1[3] = jj_gen;

    }
  }

  static final public void variavel() throws ParseException {
    RecoverySet g = First.variable;
    try {
      jj_consume_token(VARIABLE);
         acaoSemantica("#6");
      variaveis();
    } catch (ParseException e) {
        if(token_source.foundLexError() == 0) {
             consumeUntil(g, e, "program");
        }
    }
  }

  static final public void constante() throws ParseException {
    RecoverySet g = First.constante;
    try {
      jj_consume_token(NOT);
      jj_consume_token(VARIABLE);
         acaoSemantica("#3");
      constantes();
    } catch (ParseException e) {
        if(token_source.foundLexError() == 0) {
              consumeUntil(g, e, "constante");
        }
    }
  }

  static final public void constantes() throws ParseException {
    RecoverySet g = First.tipo;
    try {
      tipo();
      jj_consume_token(IS);
      lista_identificadores_de_constantes();
         acaoSemantica("#4");
      valor();
         acaoSemantica("#5");
      jj_consume_token(PONTO);
      constante_recursiva();
    } catch (ParseException e) {
        if(token_source.foundLexError() == 0) {
             consumeUntil(g, e, "constante");
        }
    }
  }

  static final public void valor() throws ParseException {
    RecoverySet g = First.valor;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CONSTANTE_NUM_INT:
        jj_consume_token(CONSTANTE_NUM_INT);
        break;
      case CONSTANTE_NUM_REAL:
        jj_consume_token(CONSTANTE_NUM_REAL);
        break;
      case CONSTANTE_LIT:
        jj_consume_token(CONSTANTE_LIT);
        break;
      case TRUE:
        jj_consume_token(TRUE);
        break;
      case FALSE:
        jj_consume_token(FALSE);
        break;
      default:
        jj_la1[4] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
        if(token_source.foundLexError() == 0) {
              consumeUntil(g, e, "valor");
        }
    }
  }

  static final public void constante_recursiva() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case BOOLEAN:
    case CHAR:
    case REAL:
    case NATURAL:
      constantes();
      break;
    default:
      jj_la1[5] = jj_gen;

    }
  }

  static final public void variaveis() throws ParseException {
    RecoverySet g = First.tipo;
    try {
      tipo();
      jj_consume_token(IS);
      lista_identificadores_variavel();
         acaoSemantica("#4");
      jj_consume_token(PONTO);
      variavel_recursiva();
    } catch (ParseException e) {
        if(token_source.foundLexError() == 0) {
            consumeUntil(g, e, "valor");
        }
    }
  }

  static final public void variavel_recursiva() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case BOOLEAN:
    case CHAR:
    case REAL:
    case NATURAL:
      variaveis();
      break;
    default:
      jj_la1[6] = jj_gen;

    }
  }

  static final public void tipo() throws ParseException {
    RecoverySet g = First.tipo;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NATURAL:
        jj_consume_token(NATURAL);
         acaoSemantica("#7");
        break;
      case REAL:
        jj_consume_token(REAL);
         acaoSemantica("#8");
        break;
      case CHAR:
        jj_consume_token(CHAR);
         acaoSemantica("#9");
        break;
      case BOOLEAN:
        jj_consume_token(BOOLEAN);
          acaoSemantica("#10");
        break;
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
         if(token_source.foundLexError() == 0) {
               consumeUntil(g, e, "valor");
         }
    }
  }

  static final public void get() throws ParseException {
    RecoverySet g = First.get;
    try {
      jj_consume_token(GET);
         acaoSemantica("#17");
      jj_consume_token(ACHAVE);
      lista_identificadores_variavel();
      jj_consume_token(FCHAVE);
      jj_consume_token(PONTO);
    } catch (ParseException e) {
        if(token_source.foundLexError() == 0) {
           consumeUntil(g, e, "valor");
        }
    }
  }

  static final public void put() throws ParseException {
    RecoverySet g = First.put;
    try {
      jj_consume_token(PUT);
      jj_consume_token(ACHAVE);
      lista_de_identificadore_constantes();
      jj_consume_token(FCHAVE);
      jj_consume_token(PONTO);
    } catch (ParseException e) {
        if(token_source.foundLexError() == 0) {
            consumeUntil(g, e, "valor");
        }
    }
  }

  static final public void lista_de_identificadore_constantes() throws ParseException {
    tipo_constante();
    lista_de_identificadore_constantes_recursivo();
  }

  static final public void tipo_constante() throws ParseException {
    RecoverySet g = First.tipo_const;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFICADOR:
        jj_consume_token(IDENTIFICADOR);
         acaoSemantica("#18");
        indice();
         acaoSemantica("#20");
        break;
      case CONSTANTE_NUM_REAL:
        jj_consume_token(CONSTANTE_NUM_REAL);
         acaoSemantica("#22");
        break;
      case CONSTANTE_LIT:
        jj_consume_token(CONSTANTE_LIT);
         acaoSemantica("#23");
        break;
      case CONSTANTE_NUM_INT:
        jj_consume_token(CONSTANTE_NUM_INT);
         acaoSemantica("#21");
        break;
      default:
        jj_la1[8] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
        if(token_source.foundLexError() == 0) {
              consumeUntil(g, e, "valor");
        }
    }
  }

  static final public void lista_de_identificadore_constantes_recursivo() throws ParseException {
    RecoverySet g = First.list_ident_const_rec;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VIRGULA:
        jj_consume_token(VIRGULA);
        lista_de_identificadore_constantes();
        break;
      default:
        jj_la1[9] = jj_gen;

      }
    } catch (ParseException e) {
          if(token_source.foundLexError() == 0) {
                 consumeUntil(g, e, "valor");
          }
    }
  }

  static final public void lista_identificadores_variavel() throws ParseException {
    RecoverySet g = First.list_ident_const_rec;
    try {
      jj_consume_token(IDENTIFICADOR);
         acaoSemantica("#12");
      indice();
         acaoSemantica("#20");
          acaoSemantica("#13");
      lista_identificadores_variavel_recursivo();
    } catch (ParseException e) {
          if(token_source.foundLexError() == 0) {
               consumeUntil(g, e, "valor");
          }
    } finally {
           acaoSemantica("#2");
    }
  }

  static final public void lista_identificadores_variavel_recursivo() throws ParseException {
    RecoverySet g = First.list_ident_const_rec;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VIRGULA:
        jj_consume_token(VIRGULA);
        lista_identificadores_variavel();
        break;
      default:
        jj_la1[10] = jj_gen;

      }
    } catch (ParseException e) {
          if(token_source.foundLexError() == 0) {
                consumeUntil(g, e, "valor");
          }
    }
  }

  static final public void lista_identificadores_de_constantes() throws ParseException {
    RecoverySet g = First.list_ident_const_rec;
    try {
      jj_consume_token(IDENTIFICADOR);
         acaoSemantica("#11");
      lista_identificadores_recursivo();
    } catch (ParseException e) {
         if(token_source.foundLexError() == 0) {
              consumeUntil(g, e, "valor");
         }
    }
  }

  static final public void lista_identificadores_recursivo() throws ParseException {
    RecoverySet g = First.list_ident_const_rec;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VIRGULA:
        jj_consume_token(VIRGULA);
        lista_identificadores_de_constantes();
        break;
      default:
        jj_la1[11] = jj_gen;

      }
    } catch (ParseException e) {
          if(token_source.foundLexError() == 0) {
               consumeUntil(g, e, "valor");
          }
    }
  }

  static final public void corpo_do_programa() throws ParseException {
    RecoverySet g = First.corp_prog;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EXECUTE:
        jj_consume_token(EXECUTE);
        jj_consume_token(ACHAVE);
        lista_de_comandos();
        jj_consume_token(FCHAVE);
        break;
      default:
        jj_la1[12] = jj_gen;

      }
    } catch (ParseException e) {
        if(token_source.foundLexError() == 0) {
                consumeUntil(g, e, "valor");
        }
    }
  }

  static final public void lista_de_comandos() throws ParseException {
    comando();
    comando_recursivo();
  }

  static final public void comando() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case GET:
      get();
      break;
    case PUT:
      put();
      break;
    case VERIFY:
      selecao();
      break;
    case SET:
      atribuicao();
      break;
    case LOOP:
    case WHILE:
      repeticao();
      break;
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void comando_recursivo() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SET:
    case GET:
    case PUT:
    case LOOP:
    case WHILE:
    case VERIFY:
      lista_de_comandos();
      break;
    default:
      jj_la1[14] = jj_gen;

    }
  }

  static final public void identificador_programa() throws ParseException {
    RecoverySet g = First.list_ident_const_rec;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFICADOR:
      try {
        jj_consume_token(IDENTIFICADOR);
      } catch (ParseException e) {
            if(token_source.foundLexError() == 0) {
                consumeUntil(g, e, "valor");
            }
      } finally {
                acaoSemantica("#2");
      }
      break;
    default:
      jj_la1[15] = jj_gen;

    }
  }

  static final public void comentario() throws ParseException {
    RecoverySet g = First.coment_prog;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMENT:
      try {
        jj_consume_token(COMENT);
        jj_consume_token(CONSTANTE_LIT);
      } catch (ParseException e) {
              if(token_source.foundLexError() == 0) {
                   consumeUntil(g, e, "valor");
              }
      }
      break;
    default:
      jj_la1[16] = jj_gen;

    }
  }

  static final public void selecao() throws ParseException {
    RecoverySet g = First.verify;
    try {
      jj_consume_token(VERIFY);
      expressao();
      isTrueFalse();
         acaoSemantica("#24");
      jj_consume_token(PONTO);
    } catch (ParseException e) {
         if(token_source.foundLexError() == 0) {
              consumeUntil(g, e, "valor");
         }
    }
  }

  static final public void isTrueFalse() throws ParseException {
    RecoverySet g = First.is;
    try {
      jj_consume_token(IS);
      trueFalse();
    } catch (ParseException e) {
        if(token_source.foundLexError() == 0) {
            consumeUntil(g, e, "valor");
        }
    }
  }

  static final public void trueFalse() throws ParseException {
    RecoverySet g = First.truefalse;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TRUE:
        jj_consume_token(TRUE);
         acaoSemantica("#25");
        jj_consume_token(ACHAVE);
        lista_de_comandos();
        jj_consume_token(FCHAVE);
        isFalse();
        break;
      case FALSE:
        jj_consume_token(FALSE);
         acaoSemantica("#26");
        jj_consume_token(ACHAVE);
        lista_de_comandos();
        jj_consume_token(FCHAVE);
        isTrue();
        break;
      default:
        jj_la1[17] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
        if(token_source.foundLexError() == 0) {
             consumeUntil(g, e, "valor");
        }
    }
  }

  static final public void isTrue() throws ParseException {
    RecoverySet g = First.is;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IS:
        jj_consume_token(IS);
        jj_consume_token(TRUE);
         acaoSemantica("#27");
        jj_consume_token(ACHAVE);
        lista_de_comandos();
        jj_consume_token(FCHAVE);
        break;
      default:
        jj_la1[18] = jj_gen;

      }
    } catch (ParseException e) {
        if(token_source.foundLexError() == 0) {
            consumeUntil(g, e, "valor");
        }
    }
  }

  static final public void isFalse() throws ParseException {
    RecoverySet g = First.is;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IS:
        jj_consume_token(IS);
        jj_consume_token(FALSE);
         acaoSemantica("#27");
        jj_consume_token(ACHAVE);
        lista_de_comandos();
        jj_consume_token(FCHAVE);
        break;
      default:
        jj_la1[19] = jj_gen;

      }
    } catch (ParseException e) {
        if(token_source.foundLexError() == 0) {
            consumeUntil(g, e, "valor");
        }
    }
  }

  static final public void atribuicao() throws ParseException {
    RecoverySet g = First.set;
    try {
      jj_consume_token(SET);
         acaoSemantica("#15");
      expressao();
      jj_consume_token(TO);
      lista_identificadores_variavel();
         acaoSemantica("#16");
      jj_consume_token(PONTO);
    } catch (ParseException e) {
        if(token_source.foundLexError() == 0) {
            consumeUntil(g, e, "valor");
        }
    }
  }

  static final public void repeticao() throws ParseException {
    RecoverySet g = First.repet;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LOOP:
        jj_consume_token(LOOP);
         acaoSemantica("#28");
        jj_consume_token(ACHAVE);
        lista_de_comandos();
        jj_consume_token(FCHAVE);
        jj_consume_token(WHILE);
        expressao();
         acaoSemantica("#29");
        jj_consume_token(IS);
        jj_consume_token(TRUE);
        jj_consume_token(PONTO);
        break;
      case WHILE:
        jj_consume_token(WHILE);
         acaoSemantica("#30");
        expressao();
         acaoSemantica("#31");
        jj_consume_token(IS);
        jj_consume_token(TRUE);
        jj_consume_token(DO);
        jj_consume_token(ACHAVE);
        lista_de_comandos();
        jj_consume_token(FCHAVE);
         acaoSemantica("#32");
        jj_consume_token(PONTO);
        break;
      default:
        jj_la1[20] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
        if(token_source.foundLexError() == 0) {
                consumeUntil(g, e, "valor");
        }
    }
  }

  static final public void expressao() throws ParseException {
    expressaoaritmeticaoulogica();
    expressao2();
  }

  static final public void expressao2() throws ParseException {
    RecoverySet g = First.exp_logic;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EQUIVALENTE:
        jj_consume_token(EQUIVALENTE);
        expressaoaritmeticaoulogica();
         acaoSemantica("#33");
        break;
      case DIFERENTE:
        jj_consume_token(DIFERENTE);
        expressaoaritmeticaoulogica();
              acaoSemantica("#34");
        break;
      case MENOR:
        jj_consume_token(MENOR);
        expressaoaritmeticaoulogica();
              acaoSemantica("#35");
        break;
      case MAIOR:
        jj_consume_token(MAIOR);
        expressaoaritmeticaoulogica();
              acaoSemantica("#36");
        break;
      case MENOROUIGUAL:
        jj_consume_token(MENOROUIGUAL);
        expressaoaritmeticaoulogica();
              acaoSemantica("#37");
        break;
      case MAIOROUIGUAL:
        jj_consume_token(MAIOROUIGUAL);
        expressaoaritmeticaoulogica();
              acaoSemantica("#38");
        break;
      default:
        jj_la1[21] = jj_gen;

      }
    } catch (ParseException e) {
        if(token_source.foundLexError() == 0) {
            consumeUntil(g, e, "valor");
        }
    }
  }

  static final public void expressaoaritmeticaoulogica() throws ParseException {
    termo2();
    menorprioridade();
  }

  static final public void menorprioridade() throws ParseException {
    RecoverySet g = First.menor_prio;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ADICAO:
        jj_consume_token(ADICAO);
        termo2();
        menorprioridade();
              acaoSemantica("#39");
        break;
      case SUBTRACAO:
        jj_consume_token(SUBTRACAO);
        termo2();
        menorprioridade();
              acaoSemantica("#40");
        break;
      case OU:
        jj_consume_token(OU);
        termo2();
        menorprioridade();
             acaoSemantica("#41");
        break;
      default:
        jj_la1[22] = jj_gen;

      }
    } catch (ParseException e) {
        if(token_source.foundLexError() == 0) {
            consumeUntil(g, e, "valor");
        }
    }
  }

  static final public void termo2() throws ParseException {
    termo1();
    mediaprioridade();
  }

  static final public void mediaprioridade() throws ParseException {
    RecoverySet g = First.media_prio;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MULTIPLICACAO:
        jj_consume_token(MULTIPLICACAO);
        termo1();
        mediaprioridade();
         acaoSemantica("#42");
        break;
      case DIVISAO:
        jj_consume_token(DIVISAO);
        termo1();
        mediaprioridade();
             acaoSemantica("#43");
        break;
      case DIVISAOINTEIRA:
        jj_consume_token(DIVISAOINTEIRA);
        termo1();
        mediaprioridade();
             acaoSemantica("#44");
        break;
      case RESTODIVISAO:
        jj_consume_token(RESTODIVISAO);
        termo1();
        mediaprioridade();
             acaoSemantica("#45");
        break;
      case E:
        jj_consume_token(E);
        termo1();
        mediaprioridade();
             acaoSemantica("#46");
        break;
      default:
        jj_la1[23] = jj_gen;

      }
    } catch (ParseException e) {
        if(token_source.foundLexError() == 0) {
            consumeUntil(g, e, "valor");
        }
    }
  }

  static final public void termo1() throws ParseException {
    elemento();
    maiorprioridade();
  }

  static final public void maiorprioridade() throws ParseException {
    RecoverySet g = First.maior_prio;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case POTENCIA:
        jj_consume_token(POTENCIA);
        elemento();
        maiorprioridade();
         acaoSemantica("#47");
        break;
      default:
        jj_la1[24] = jj_gen;

      }
    } catch (ParseException e) {
        if(token_source.foundLexError() == 0) {
            consumeUntil(g, e, "valor");
        }
    }
  }

  static final public void elemento() throws ParseException {
    RecoverySet g = First.elemento;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFICADOR:
        jj_consume_token(IDENTIFICADOR);
         acaoSemantica("#19");
        indice();
             acaoSemantica("#20");
        break;
      case CONSTANTE_NUM_INT:
        jj_consume_token(CONSTANTE_NUM_INT);
         acaoSemantica("#21");
        break;
      case CONSTANTE_NUM_REAL:
        jj_consume_token(CONSTANTE_NUM_REAL);
             acaoSemantica("#22");
        break;
      case CONSTANTE_LIT:
        jj_consume_token(CONSTANTE_LIT);
             acaoSemantica("#23");
        break;
      case TRUE:
        jj_consume_token(TRUE);
             acaoSemantica("#48");
        break;
      case FALSE:
        jj_consume_token(FALSE);
             acaoSemantica("#49");
        break;
      case APARENT:
        jj_consume_token(APARENT);
        expressao();
        jj_consume_token(FPARENT);
        break;
      case NAO:
        jj_consume_token(NAO);
        jj_consume_token(APARENT);
        expressao();
        jj_consume_token(FPARENT);
              acaoSemantica("#50");
        break;
      default:
        jj_la1[25] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
        if(token_source.foundLexError() == 0) {
            consumeUntil(g, e, "valor");
        }
    }
  }

  static final public void indice() throws ParseException {
    RecoverySet g = First.indice;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ACOLCH:
        jj_consume_token(ACOLCH);
        jj_consume_token(CONSTANTE_NUM_INT);
        acaoSemantica("#14");
        jj_consume_token(FCOLCH);
        break;
      default:
        jj_la1[26] = jj_gen;

      }
    } catch (ParseException e) {
        if(token_source.foundLexError() == 0) {
             consumeUntil(g, e, "valor");
         }
    }
  }

  static final public void Programa() throws ParseException {
    program();
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public AnalisadorLexicoTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[27];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x40,0x180,0x100,0x80,0x1c300000,0x3c00,0x3c00,0x3c00,0x1e000000,0x0,0x0,0x0,0x4000,0x10f8000,0x10f8000,0x2000000,0x0,0x300000,0x200,0x200,0xc0000,0x0,0x0,0x0,0x0,0x9e300000,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x20,0x20,0x20,0x0,0x0,0x0,0x0,0x80,0x0,0x0,0x0,0x0,0x3f0000,0x800300,0x1006c00,0x1000,0x400000,0x8,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }

  /** Constructor with InputStream. */
  public AnalisadorLexico(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public AnalisadorLexico(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new AnalisadorLexicoTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
      mensagens_erros_sintatic = new StringBuffer();
      nCountSintaticError = 0;
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public AnalisadorLexico(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new AnalisadorLexicoTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public AnalisadorLexico(AnalisadorLexicoTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(AnalisadorLexicoTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
      if(token_source.foundLexError() >  0) throw generateParseException();
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
      if(token_source.foundLexError() >  0) return -1;
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List jj_expentries = new java.util.ArrayList();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[69];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 27; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 69; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
