/* Generated By:JavaCC: Do not edit this line. AnalisadorLexicoConstants.java */
package Analisadores;
/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalisadorLexicoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROGRAM = 1;
  /** RegularExpression Id. */
  int DEFINE = 2;
  /** RegularExpression Id. */
  int NOT = 3;
  /** RegularExpression Id. */
  int VARIABLE = 4;
  /** RegularExpression Id. */
  int IS = 5;
  /** RegularExpression Id. */
  int BOOLEAN = 6;
  /** RegularExpression Id. */
  int CHAR = 7;
  /** RegularExpression Id. */
  int REAL = 8;
  /** RegularExpression Id. */
  int NATURAL = 9;
  /** RegularExpression Id. */
  int EXECUTE = 10;
  /** RegularExpression Id. */
  int SET = 11;
  /** RegularExpression Id. */
  int GET = 12;
  /** RegularExpression Id. */
  int PUT = 13;
  /** RegularExpression Id. */
  int LOOP = 14;
  /** RegularExpression Id. */
  int WHILE = 15;
  /** RegularExpression Id. */
  int TRUE = 16;
  /** RegularExpression Id. */
  int FALSE = 17;
  /** RegularExpression Id. */
  int DO = 18;
  /** RegularExpression Id. */
  int TO = 19;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 20;
  /** RegularExpression Id. */
  int CONSTANTE_NUM_REAL = 21;
  /** RegularExpression Id. */
  int CONSTANTE_NUM_INT = 22;
  /** RegularExpression Id. */
  int CONSTANTE_LIT = 23;
  /** RegularExpression Id. */
  int ASCII = 24;
  /** RegularExpression Id. */
  int LETTER = 25;
  /** RegularExpression Id. */
  int COMENTARIO_LINHA = 26;
  /** RegularExpression Id. */
  int COMENTARIO_BLOCO = 27;
  /** RegularExpression Id. */
  int CHARESP = 28;
  /** RegularExpression Id. */
  int LETRA = 29;
  /** RegularExpression Id. */
  int APARENT = 30;
  /** RegularExpression Id. */
  int FPARENT = 31;
  /** RegularExpression Id. */
  int ACHAVE = 32;
  /** RegularExpression Id. */
  int FCHAVE = 33;
  /** RegularExpression Id. */
  int ACOLCH = 34;
  /** RegularExpression Id. */
  int FCOLCH = 35;
  /** RegularExpression Id. */
  int VIRGULA = 36;
  /** RegularExpression Id. */
  int PONTO = 37;
  /** RegularExpression Id. */
  int COMENT = 38;
  /** RegularExpression Id. */
  int ADICAO = 39;
  /** RegularExpression Id. */
  int SUBTRACAO = 40;
  /** RegularExpression Id. */
  int MULTIPLICACAO = 41;
  /** RegularExpression Id. */
  int DIVISAO = 42;
  /** RegularExpression Id. */
  int POTENCIA = 43;
  /** RegularExpression Id. */
  int DIVISAOINTEIRA = 44;
  /** RegularExpression Id. */
  int RESTODIVISAO = 45;
  /** RegularExpression Id. */
  int IGUAL = 46;
  /** RegularExpression Id. */
  int EQUIVALENTE = 47;
  /** RegularExpression Id. */
  int DIFERENTE = 48;
  /** RegularExpression Id. */
  int MENOR = 49;
  /** RegularExpression Id. */
  int MENOROUIGUAL = 50;
  /** RegularExpression Id. */
  int MAIOR = 51;
  /** RegularExpression Id. */
  int MAIOROUIGUAL = 52;
  /** RegularExpression Id. */
  int NAO = 53;
  /** RegularExpression Id. */
  int OU = 54;
  /** RegularExpression Id. */
  int E = 55;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<PROGRAM>",
    "<DEFINE>",
    "<NOT>",
    "<VARIABLE>",
    "<IS>",
    "<BOOLEAN>",
    "<CHAR>",
    "<REAL>",
    "<NATURAL>",
    "<EXECUTE>",
    "<SET>",
    "<GET>",
    "<PUT>",
    "<LOOP>",
    "<WHILE>",
    "<TRUE>",
    "<FALSE>",
    "<DO>",
    "<TO>",
    "<IDENTIFICADOR>",
    "<CONSTANTE_NUM_REAL>",
    "<CONSTANTE_NUM_INT>",
    "<CONSTANTE_LIT>",
    "<ASCII>",
    "<LETTER>",
    "<COMENTARIO_LINHA>",
    "<COMENTARIO_BLOCO>",
    "<CHARESP>",
    "<LETRA>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\".\"",
    "\":-\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"**\"",
    "\"%\"",
    "\"%%\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"!\"",
    "\"|\"",
    "\"&\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\f\"",
    "\"\\r\\n\"",
    "\" \"",
  };

}
