package interfacecompilador;


import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.concurrent.CountDownLatch;

public class Tela_execucao extends javax.swing.JFrame {
    // Variables declaration - do not modify
    private javax.swing.JTextArea areaTextExecution;
    private javax.swing.JButton envia;
    private javax.swing.JTextField inputExecution;
    private javax.swing.JScrollPane jScrollPane1;
    private String textoExecucao = "";
    public volatile boolean finalizou = false;
    public volatile boolean enviou = false;
    public boolean entrada_invalida = false;
    private String textoImput = "";
    // End of variables declaration
    public Tela_execucao(){
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        areaTextExecution = new javax.swing.JTextArea();
        inputExecution = new javax.swing.JTextField();
        envia = new javax.swing.JButton();

        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                setVisible(false);
                finalizou = true;
            }
        });
        KeyListener keyAction = new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {

            }

            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    if(inputExecution.getText().trim().length() > 0){
                        textoImput = inputExecution.getText().trim();
                        textoExecucao += " " + inputExecution.getText().trim() + "\n";
                        areaTextExecution.setText(textoExecucao);
                        inputExecution.setText("");
                        enviou = true;
                        setDisableInput();
                    }else{
                        entrada_invalida = true;
                    }
                }
            }

            @Override
            public void keyReleased(KeyEvent e) {

            }
        };
        Tela_execucao.getFrames()[0].addKeyListener(keyAction);
        areaTextExecution.setColumns(20);
        areaTextExecution.setRows(5);
        areaTextExecution.setEnabled(false);
        areaTextExecution.setDisabledTextColor(Color.BLACK);
        areaTextExecution.setText(textoExecucao);
        jScrollPane1.setViewportView(areaTextExecution);
        inputExecution.addKeyListener(keyAction);

        envia.setText("Envia");
        envia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(inputExecution)
                                                .addGap(18, 18, 18)
                                                .addComponent(envia)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(inputExecution))
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(envia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>
    private void inputExecutionActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void enviaActionPerformed(java.awt.event.ActionEvent evt) {
        if(inputExecution.getText().trim().length() > 0) {
            textoImput = inputExecution.getText().trim();
            textoExecucao += " " + inputExecution.getText().trim() + "\n";
            inputExecution.setText("");
            areaTextExecution.setText(textoExecucao);
            enviou = true;
        } else{
                entrada_invalida = true;
        }
    }
    public boolean isInput(){
        return enviou;
    }

    public void getInput() throws InterruptedException {
        inputExecution.requestFocus();
        final CountDownLatch latch = new CountDownLatch(1);
        // Anonymous class invoked from EDT
        KeyEventDispatcher dispatcher = e -> {
            if (e.getKeyCode() == KeyEvent.VK_ENTER || enviou) latch.countDown(); return false;
        };
        KeyboardFocusManager.getCurrentKeyboardFocusManager().addKeyEventDispatcher(dispatcher);
        latch.await();
        // current thread waits here until countDown() is called
        KeyboardFocusManager.getCurrentKeyboardFocusManager().removeKeyEventDispatcher(dispatcher);
        String input = inputExecution.getText();
        inputExecution.setText("");
        setDisableInput();
        if(input.trim().length() > 1){
            enviou = true;
            textoImput = input;
        }

        inputExecution.setCaretPosition(0);
    }
    public String getTextoImput(){

        inputExecution.setVisible(true);
        if(entrada_invalida ==  true){
            entrada_invalida = false;
            return "invalido";
        }
        setDisableInput();
        return this.textoImput;
    }
    public void setTexto(String texto){
        String atual = areaTextExecution.getText();
        textoExecucao =atual + "\n" + texto;
        areaTextExecution.setText(textoExecucao);
    }
    public  void setDisableInput(){
        inputExecution.setEnabled(false);
        envia.setEnabled(false);
    }
    public  void setEnableInput(){
        inputExecution.setEnabled(true);
        envia.setEnabled(true);
    }
    public void run(){

    }

}
